# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_exam_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1027, 716)
        self.pa_text = QtWidgets.QPlainTextEdit(Dialog)
        self.pa_text.setGeometry(QtCore.QRect(390, 580, 231, 51))
        self.pa_text.setObjectName("pa_text")
        self.button_status = QtWidgets.QPushButton(Dialog)
        self.button_status.setGeometry(QtCore.QRect(460, 660, 100, 36))
        self.button_status.setObjectName("button_status")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 50, 640, 480))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_status.setText(_translate("Dialog", "Submit"))
